### ISSUE TITLE
Buttons on the shutdown dialog are black

### ISSUE THREAD

**Issue by bgklc** [fujimo-t/gnome-shell-theme-e-ink#10]
…and no text can be read  ![8D5160CF-3881-4582-ADEA-A669EC948224](https://user-images.githubusercontent.com/930395/197325769-29e19798-11a1-459e-835c-c987522bf300.jpeg)

**Comment by fujimo-t** [comment]
Not black in my environment (GNOME 42 on Fedora 36 + v2.1.0 of this theme).
![image](https://user-images.githubusercontent.com/10286050/197327099-66f2fbc7-399a-4589-94a8-fc33cceebcc7.png)

Could you tell me your GNOME and this theme versions?

**Comment by bgklc** [comment]
gnome 42.4
theme 2.1.0
fedora 36 as well

**Comment by bgklc** [comment]
Sorry, on another user on the same machine with seemingly same settings regarding themes I see all OK:
![image](https://user-images.githubusercontent.com/930395/197688478-67cf8464-a711-4684-8b62-6861eaba96a4.jpeg)

**Comment by fujimo-t** [comment]
I confirmed this by tunning E-Ink display parameter to more dark.

Dialog buttons are relatively darker than other components so it seems better to change to more bright.

**Comment by fujimo-t** [comment]
It seems to be solved on `v46.1.0` by rebasing to the default high contrast theme.
