### ISSUE TITLE
other desktop environments?

### ISSUE THREAD

**Issue by axel9546** [fujimo-t/gnome-shell-theme-e-ink#11]
Hi! 
is it possible to use this GNOME theme for other DE such as LFCE?

**Comment by fujimo-t** [comment]
No, it isn't possible.

I don't know DE named LFCE.
Isn't typo of Xfce or LXDE?

**Comment by axel9546** [comment]
yes sorry Xfce

Il giorno ven 30 dic 2022 alle ore 13:22 fujimo-t ***@***.***>
ha scritto:

**Comment by fujimo-t** [comment]
I got it.
