### ISSUE TITLE
White icons in applications and dock on white background

### ISSUE THREAD

**Issue by Bushstar** [fujimo-t/gnome-shell-theme-e-ink#12]
Clean install of Ubuntu 22.04 and have white icons in the dock and the applications menu, these icons are invisible on my eink. I've managed to change the background colour to black on the dock so I can see the icons.

I'm pretty sure that the icons were black before so stood out on a white background.

**Comment by fujimo-t** [comment]
I confirmed it on Ubuntu 22.04.

There aren't any problem on vanilla GNOME such as Fedora so I guess that some color specified as `important` (can't override) by default Ubuntu theme.

I`ll try to fix it.

**Comment by fujimo-t** [comment]
@Bushstar Fixed on [42.1.1](https://github.com/fujimo-t/gnome-shell-theme-e-ink/releases/tag/v42.1.1). Could you try it?

**Comment by Bushstar** [comment]
@fujimo-t Excellent work. That has fixed the issue.
