### ISSUE TITLE
Ubuntu dock has dark background 

### ISSUE THREAD

**Issue by fujimo-t** [fujimo-t/gnome-shell-theme-e-ink#2]
Move from https://github.com/fujimo-t/gnome-shell-extension-e-ink-mode/issues/4.

I confirmed it on Ubuntu 21.10.

**Comment by fujimo-t** [comment]
I won't fix it.

The dock is styled by CSS classes for [Dash to Dock](https://github.com/micheleg/dash-to-dock).
`gnome-shell-theme-e-ink` targets to GNOME Shell only and not to specific extensions.

Ubuntu's `Ubuntu Dock` extension is fork of `Dash to Dock` and original `Dash to Dock` supports a function to adapt it's looks to current GNOME Shell theme.
@Bushstar You can disable `Ubuntu Dock` and install `Dash to Dock` to change color of the dock background.

**Comment by Bushstar** [comment]
Thanks for the info, will follow your advice when I upgrade Ubuntu. I ended up moving back to 20.04.

**Comment by Bushstar** [comment]
On a laptop running Ubuntu 21.10 to get the old Dock back I did the following.

Disable existing Dock.
gnome-extensions disable ubuntu-dock@ubuntu.com

Install Gnome Dash to Dock
https://micheleg.github.io/dash-to-dock/index.html

Enable Gnome Dash to Dock
gnome-extensions enable dash-to-dock@micxgx.gmail.com

Configure Gnome Dash to Dock
gnome-shell-extension-prefs dash-to-dock@micxgx.gmail.com

For Ubuntu behaviour use the following options.

Position on screen    Left
Intelligent autohide    Disabled
Panel mode               Ticked
