### ISSUE TITLE
Colors in the calendar are suboptimal

### ISSUE THREAD

**Issue by tkoeck** [fujimo-t/gnome-shell-theme-e-ink#9]
Hi,

thanks for that shell theme. I do also have an e-ink monitor, but at the moment I am using it on my LCD work monitor because it is so neat and clean. 

It's nice, but the calendar colors with a bright green aren't that good for the weekday days. I doubt it's readable on an e-ink monitor that way, too.

![Screenshot from 2022-10-17 19-04-30](https://user-images.githubusercontent.com/42435353/196239663-727a9526-991f-425d-bac0-0ae8523e5633.png)

**Comment by tkoeck** [comment]
System is a Debian 11 AMD64 with the default Gnome installed.

**Comment by fujimo-t** [comment]
The weekday color looks black in my GNOME 42 on Fedora 36.
![calendar_fedora36_gnome42](https://user-images.githubusercontent.com/10286050/197214040-4e6ea66c-8829-452c-9e07-a54f6c1e637f.png)

What version is your GNOME?

**Comment by tkoeck** [comment]
Thanks for the fast reply. I use the standard version of Debian 11.

```
tkoeck@tron-nb:~$ apt-cache show gnome
Package: gnome
Source: meta-gnome3
Version: 1:3.38+3
Installed-Size: 35
Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Architecture: amd64
```

**Comment by tkoeck** [comment]
Unfortunately, Gnome 42 will be released with Debian 12. Sometime in the next year.

**Comment by fujimo-t** [comment]
Sometime shell theme specification are not compatible between different GNOME versions.

Can you try [v1.0.0](https://github.com/fujimo-t/gnome-shell-theme-e-ink/releases/tag/v1.0.0)?
It's target GNOME 40 so maybe better than [v2.1.0](https://github.com/fujimo-t/gnome-shell-theme-e-ink/releases/tag/v2.1.0).

**Comment by fujimo-t** [comment]
I installed Debian 11 with GNOME 3.38 and v1.0.0 works fine.
I recommend to use v1.0.0 for GNOME 3.38.
![image](https://user-images.githubusercontent.com/10286050/197326650-82222f4a-ddf9-4483-a9c7-fd2027cb0ea6.png)

**Comment by tkoeck** [comment]
Thanks for checking it out. I'll try it out.

**Comment by tkoeck** [comment]
> Sometime shell theme specification are not compatible between different GNOME versions.
> 
> Can you try [v1.0.0](https://github.com/fujimo-t/gnome-shell-theme-e-ink/releases/tag/v1.0.0)? It's target GNOME 40 so maybe better than [v2.1.0](https://github.com/fujimo-t/gnome-shell-theme-e-ink/releases/tag/v2.1.0).

With version 1.0.0 it works again. Thanks a lot. Still, it's a little bit strange that it won't work with later versions. ;-)

**Comment by fujimo-t** [comment]
Sadly, maintain a theme against multi GNOME versions is difficult, so each version of this theme targets only specific GNOME version.

**Comment by tkoeck** [comment]
Okay, thanks for the help.
